name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: [self-hosted, linux, amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and Inspect Buildx Builder
        run: |
          docker buildx rm mybuilder || true
          docker buildx create --driver docker --use --name mybuilder
          docker buildx inspect --bootstrap
          docker buildx ls

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- PASSO CORRIGIDO ---
      - name: Print DOCKER_REGISTRY_HOST for debugging
        run: | # <--- Adicione este | (pipe) aqui
          echo "DOCKER_REGISTRY_HOST used: ${{ secrets.DOCKER_REGISTRY_HOST }}"
      # --- FIM DO PASSO CORRIGIDO ---

      - name: Build and Push Docker image for AMD64
        run: |
          docker buildx build \
            --builder mybuilder \
            -t ${{ secrets.DOCKER_REGISTRY_HOST }}/bgls:latest \
            --push \
            .

      - name: Deploy application on Ubuntu Server
        run: |
          /home/YOUR_UBUNTU_USER/bgls-app/deploy.sh
