name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Inspect Buildx Builders (after setup)
        run: |
          docker buildx inspect # Inspeciona o builder ativo (que agora ser√° 'default' com driver 'docker')
          docker buildx ls      # Lista todos os builders

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print DOCKER_REGISTRY_HOST for debugging
        run: |
          echo "DOCKER_REGISTRY_HOST used: ${{ secrets.DOCKER_REGISTRY_HOST }}"

      - name: Build and Push Docker image for AMD64
        run: |
          docker buildx build \
            -t ${{ secrets.DOCKER_REGISTRY_HOST }}/bgls:latest \
            --push \
            .
      - name: Deploy application on Ubuntu Server
        run: |
          /home/YOUR_UBUNTU_USER/bgls-app/deploy.sh
