name: CI/CD Pipeline

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build_and_push:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Inspect Buildx Builders (after setup)
        run: |
          docker buildx inspect # Inspeciona o builder ativo (que agora ser치 'default' com driver 'docker')
          docker buildx ls      # Lista todos os builders

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image for AMD64
        run: |
          docker buildx build \
            -t ${{ secrets.DOCKER_REGISTRY_HOST }}/bgls:latest \
            --push \
            .

  sonar_analysis:
    needs: build_and_push
    runs-on: [self-hosted]
    if: success()

    steps:
      - name: Checkout code # Pega o c칩digo novamente (necess치rio para o scanner do Sonar)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Essencial para o SonarQube analisar o hist칩rico de commits

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=BGLS -Dsonar.projectName='BGLS'

  deploy:
    needs: build_and_push
    runs-on: [self-hosted]
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Deploy application on Ubuntu Server
        run: |
          /home/bruno/bgls-app/deploy.sh
